### ISSUE TITLE
Dependency charts get bumped

### ISSUE THREAD

**Issue by HanwhaARudolph** [ArieLevs/PyBump#39]
**Describe the bug**
When a chart has dependent charts, it will bump the dependency version as well
 
**To Reproduce**
1. Create a helm chart with dependencies (https://v3-1-0.helm.sh/docs/helm/helm_dependency/)
2. Run pybump
3. All versions get bumped

**Expected behavior**
Only the root chart version is bumped

**System information:**
ALL

**Comment by ArieLevs** [comment]
Hi @HanwhaARudolph 

I was not able to reproduce this bug, using a `Chart.yaml` file with content:
```yaml
apiVersion: v1
appVersion: 1.0.6-metedata
dependencies:
- name: some-dependancy-chart
  repository: https://some.dependancy.repo
  version: v3.0.1
- name: another-dependancy-chart
  repository: https://some.dependancy.repo
  version: 16.0.0
description: A Helm chart for Kubernetes
name: test
version: 2.2.5
```

executing
```shell
pybump bump --file ./Chart.yaml --level patch
pybump bump --file ./Chart.yaml --level minor
pybump bump --file ./Chart.yaml --level patch --app-version
```

all resulted with a valid bump when the dependancies charts were not updated,

is this the scenario u had the bug with?
which pybump version are you using?
